#8.	Write a program to print numbers from 10 down to 1.
#[Hint: first check the sequence generated by range function on IDLE using this command i.e. list(range(10, 0, -1))]

for i in range(10,0,-1):
    print(i)
